// PROTOTYPE — throwaway fixture data, not production

export type { Category, MenuItem, Restaurant } from "@/themes/types";
export { CATEGORY_LABELS } from "@/themes/types";

import type { Restaurant } from "@/themes/types";

export const FIXTURE: Restaurant = {
  name: "The Golden Fork",
  tagline: "Modern European cuisine · Est. 2019",
  theme: "warm",
  enabledCategories: ["specials", "appetizers", "mains", "drinks", "desserts"],
  items: [
    {
      id: "1",
      name: "Wagyu Smash Burger",
      description: "8oz wagyu patty, aged cheddar, caramelized onions, truffle aioli on a brioche bun",
      price: 34,
      category: "specials",
      imageUrl: "https://picsum.photos/seed/burger42/600/400",
      isFeatured: true,
      isAvailable: true,
    },
    {
      id: "2",
      name: "Truffle Pappardelle",
      description: "House-made pasta, black truffle, parmesan cream, fresh herbs, toasted breadcrumbs",
      price: 28,
      category: "mains",
      imageUrl: "https://picsum.photos/seed/pasta17/600/400",
      isFeatured: true,
      isAvailable: true,
    },
    {
      id: "3",
      name: "Burrata",
      description: "Fresh burrata, heirloom tomatoes, basil oil, aged balsamic, flaky sea salt",
      price: 18,
      category: "appetizers",
      imageUrl: "https://picsum.photos/seed/burrata9/600/400",
      isFeatured: false,
      isAvailable: true,
    },
    {
      id: "4",
      name: "Crispy Calamari",
      description: "Lightly battered, lemon aioli, pickled chili, fresh herbs",
      price: 16,
      category: "appetizers",
      imageUrl: "https://picsum.photos/seed/calamari3/600/400",
      isFeatured: false,
      isAvailable: true,
    },
    {
      id: "5",
      name: "Prime Ribeye",
      description: "12oz dry-aged ribeye, seasonal vegetables, red wine jus, bone marrow butter",
      price: 52,
      category: "mains",
      imageUrl: "https://picsum.photos/seed/steak88/600/400",
      isFeatured: false,
      isAvailable: true,
    },
    {
      id: "6",
      name: "Pan-Seared Salmon",
      description: "Atlantic salmon, lemon butter sauce, braised greens, preserved lemon",
      price: 36,
      category: "mains",
      imageUrl: "https://picsum.photos/seed/salmon55/600/400",
      isFeatured: false,
      isAvailable: true,
    },
    {
      id: "7",
      name: "Espresso Martini",
      description: "Vodka, fresh espresso, coffee liqueur, vanilla sugar",
      price: 16,
      category: "drinks",
      imageUrl: "https://picsum.photos/seed/cocktail22/600/400",
      isFeatured: false,
      isAvailable: true,
    },
    {
      id: "8",
      name: "Old Fashioned",
      description: "Makers Mark bourbon, Angostura bitters, orange peel, Luxardo cherry",
      price: 14,
      category: "drinks",
      imageUrl: "https://picsum.photos/seed/oldfashioned7/600/400",
      isFeatured: false,
      isAvailable: true,
    },
    {
      id: "9",
      name: "Tiramisu",
      description: "Mascarpone cream, espresso-soaked ladyfingers, dark cocoa dusting",
      price: 12,
      category: "desserts",
      imageUrl: "https://picsum.photos/seed/tiramisu4/600/400",
      isFeatured: false,
      isAvailable: true,
    },
    {
      id: "10",
      name: "Chocolate Lava Cake",
      description: "Warm 70% cacao cake, molten center, vanilla bean ice cream, raspberry coulis",
      price: 14,
      category: "desserts",
      imageUrl: "https://picsum.photos/seed/lavacake6/600/400",
      isFeatured: false,
      isAvailable: true,
    },
  ],
};
